git:
  paging:
    colorArg: always
    pager: diff-so-fancy
  mainBranches:
    # updated to add "develop"
    - master
    - main
    - develop
gui:
  skipDiscardChangeWarning: true
keybinding:
  universal:
    # temporarily disable it, as it is used in tig,
    # and I sometimes accidentally access it
    quit: <disabled>
